In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.stats import sem
from scipy.stats import linregress
from pprint import pprint


election_data_all_csv = "Resources/election_all.csv"

In [2]:
election_data_all= pd.read_csv(election_data_all_csv)
election_data_all

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
0,2000,Alabama,AL,Autauga,1001.0,President,Al Gore,democrat,4942.0,17208,20191203
1,2000,Alabama,AL,Autauga,1001.0,President,George W. Bush,republican,11993.0,17208,20191203
2,2000,Alabama,AL,Autauga,1001.0,President,Ralph Nader,green,160.0,17208,20191203
3,2000,Alabama,AL,Autauga,1001.0,President,Other,NaN,113.0,17208,20191203
4,2000,Alabama,AL,Baldwin,1003.0,President,Al Gore,democrat,13997.0,56480,20191203
...,...,...,...,...,...,...,...,...,...,...,...
50519,2016,Alaska,AK,District 40,2040.0,President,Donald Trump,republican,1377.0,4610,20191203
50520,2016,Alaska,AK,District 40,2040.0,President,Other,NaN,895.0,4610,20191203
50521,2016,Alaska,NaN,District 99,2099.0,President,Hillary Clinton,democrat,274.0,5056,20191203
50522,2016,Alaska,NaN,District 99,2099.0,President,Donald Trump,republican,40.0,5056,20191203
50523,2016,Alaska,NaN,District 99,2099.0,President,Other,NaN,28.0,5056,20191203

In [4]:
election_data_all_dropNA = election_data_all.dropna()

In [5]:
election_data_2016_1 = election_data_all_dropNA[election_data_all_dropNA['year']==2016]
election_data_2016_1

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
40517,2016,Alabama,AL,Autauga,1001.0,President,Hillary Clinton,democrat,5936.0,24973,20191203
40518,2016,Alabama,AL,Autauga,1001.0,President,Donald Trump,republican,18172.0,24973,20191203
40520,2016,Alabama,AL,Baldwin,1003.0,President,Hillary Clinton,democrat,18458.0,95215,20191203
40521,2016,Alabama,AL,Baldwin,1003.0,President,Donald Trump,republican,72883.0,95215,20191203
40523,2016,Alabama,AL,Barbour,1005.0,President,Hillary Clinton,democrat,4871.0,10469,20191203
...,...,...,...,...,...,...,...,...,...,...,...
50513,2016,Alaska,AK,District 38,2038.0,President,Donald Trump,republican,1143.0,5095,20191203
50515,2016,Alaska,AK,District 39,2039.0,President,Hillary Clinton,democrat,3142.0,5639,20191203
50516,2016,Alaska,AK,District 39,2039.0,President,Donald Trump,republican,1405.0,5639,20191203
50518,2016,Alaska,AK,District 40,2040.0,President,Hillary Clinton,democrat,2338.0,4610,20191203
50519,2016,Alaska,AK,District 40,2040.0,President,Donald Trump,republican,1377.0,4610,20191203

In [6]:
election_data_2016_2 = election_data_2016_1.drop(columns=['FIPS', 'version', 'office'])
election_data_2016_2

,year,state,state_po,county,candidate,party,candidatevotes,totalvotes
40517,2016,Alabama,AL,Autauga,Hillary Clinton,democrat,5936.0,24973
40518,2016,Alabama,AL,Autauga,Donald Trump,republican,18172.0,24973
40520,2016,Alabama,AL,Baldwin,Hillary Clinton,democrat,18458.0,95215
40521,2016,Alabama,AL,Baldwin,Donald Trump,republican,72883.0,95215
40523,2016,Alabama,AL,Barbour,Hillary Clinton,democrat,4871.0,10469
...,...,...,...,...,...,...,...,...
50513,2016,Alaska,AK,District 38,Donald Trump,republican,1143.0,5095
50515,2016,Alaska,AK,District 39,Hillary Clinton,democrat,3142.0,5639
50516,2016,Alaska,AK,District 39,Donald Trump,republican,1405.0,5639
50518,2016,Alaska,AK,District 40,Hillary Clinton,democrat,2338.0,4610
50519,2016,Alaska,AK,District 40,Donald Trump,republican,1377.0,4610

In [7]:
election_data_2016_3 = election_data_2016_2.reset_index(drop=True)

In [8]:
election_data_2016_3.columns=["year", "state", "state_code", "county", "candidate", "party", "candidate_votes", "total_votes"]
election_data_2016_3

,year,state,state_code,county,candidate,party,candidate_votes,total_votes
0,2016,Alabama,AL,Autauga,Hillary Clinton,democrat,5936.0,24973
1,2016,Alabama,AL,Autauga,Donald Trump,republican,18172.0,24973
2,2016,Alabama,AL,Baldwin,Hillary Clinton,democrat,18458.0,95215
3,2016,Alabama,AL,Baldwin,Donald Trump,republican,72883.0,95215
4,2016,Alabama,AL,Barbour,Hillary Clinton,democrat,4871.0,10469
...,...,...,...,...,...,...,...,...
6301,2016,Alaska,AK,District 38,Donald Trump,republican,1143.0,5095
6302,2016,Alaska,AK,District 39,Hillary Clinton,democrat,3142.0,5639
6303,2016,Alaska,AK,District 39,Donald Trump,republican,1405.0,5639
6304,2016,Alaska,AK,District 40,Hillary Clinton,democrat,2338.0,4610
6305,2016,Alaska,AK,District 40,Donald Trump,republican,1377.0,4610