In [6]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.stats import sem
from scipy.stats import linregress
from pprint import pprint


election_data_all_csv = "Resources/election_all.csv"

In [7]:
election_data_all= pd.read_csv(election_data_all_csv)
election_data_all

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
0,2000,Alabama,AL,Autauga,1001.0,President,Al Gore,democrat,4942.0,17208,20191203
1,2000,Alabama,AL,Autauga,1001.0,President,George W. Bush,republican,11993.0,17208,20191203
2,2000,Alabama,AL,Autauga,1001.0,President,Ralph Nader,green,160.0,17208,20191203
3,2000,Alabama,AL,Autauga,1001.0,President,Other,NaN,113.0,17208,20191203
4,2000,Alabama,AL,Baldwin,1003.0,President,Al Gore,democrat,13997.0,56480,20191203
...,...,...,...,...,...,...,...,...,...,...,...
50519,2016,Alaska,AK,District 40,2040.0,President,Donald Trump,republican,1377.0,4610,20191203
50520,2016,Alaska,AK,District 40,2040.0,President,Other,NaN,895.0,4610,20191203
50521,2016,Alaska,NaN,District 99,2099.0,President,Hillary Clinton,democrat,274.0,5056,20191203
50522,2016,Alaska,NaN,District 99,2099.0,President,Donald Trump,republican,40.0,5056,20191203
50523,2016,Alaska,NaN,District 99,2099.0,President,Other,NaN,28.0,5056,20191203

In [11]:
election_data_all_dropNA = election_data_all.dropna()

In [12]:
election_data_2004_1 = election_data_all_dropNA[election_data_all_dropNA['year']==2004]
election_data_2004_1

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
12464,2004,Alabama,AL,Autauga,1001.0,President,John Kerry,democrat,4758.0,20081,20191203
12465,2004,Alabama,AL,Autauga,1001.0,President,George W. Bush,republican,15196.0,20081,20191203
12467,2004,Alabama,AL,Baldwin,1003.0,President,John Kerry,democrat,15599.0,69320,20191203
12468,2004,Alabama,AL,Baldwin,1003.0,President,George W. Bush,republican,52971.0,69320,20191203
12470,2004,Alabama,AL,Barbour,1005.0,President,John Kerry,democrat,4832.0,10777,20191203
...,...,...,...,...,...,...,...,...,...,...,...
50144,2004,Alaska,AK,District 38,2038.0,President,George W. Bush,republican,2459.0,5075,20191203
50146,2004,Alaska,AK,District 39,2039.0,President,John Kerry,democrat,2365.0,5568,20191203
50147,2004,Alaska,AK,District 39,2039.0,President,George W. Bush,republican,2881.0,5568,20191203
50149,2004,Alaska,AK,District 40,2040.0,President,John Kerry,democrat,2328.0,5788,20191203
50150,2004,Alaska,AK,District 40,2040.0,President,George W. Bush,republican,3217.0,5788,20191203

In [27]:
election_data_2004_2 = election_data_2004_1.drop(columns=['FIPS', 'version', 'office'])
election_data_2004_2

,year,state,state_po,county,candidate,party,candidatevotes,totalvotes
12464,2004,Alabama,AL,Autauga,John Kerry,democrat,4758.0,20081
12465,2004,Alabama,AL,Autauga,George W. Bush,republican,15196.0,20081
12467,2004,Alabama,AL,Baldwin,John Kerry,democrat,15599.0,69320
12468,2004,Alabama,AL,Baldwin,George W. Bush,republican,52971.0,69320
12470,2004,Alabama,AL,Barbour,John Kerry,democrat,4832.0,10777
...,...,...,...,...,...,...,...,...
50144,2004,Alaska,AK,District 38,George W. Bush,republican,2459.0,5075
50146,2004,Alaska,AK,District 39,John Kerry,democrat,2365.0,5568
50147,2004,Alaska,AK,District 39,George W. Bush,republican,2881.0,5568
50149,2004,Alaska,AK,District 40,John Kerry,democrat,2328.0,5788
50150,2004,Alaska,AK,District 40,George W. Bush,republican,3217.0,5788

In [30]:
election_data_2004_3 = election_data_2004_2.reset_index(drop=True)

In [35]:
election_data_2004_3.columns=["year", "state", "state_code", "county", "candidate", "party", "candidate_votes", "total_votes"]
election_data_2004_3

,year,state,state_code,county,candidate,party,candidate_votes,total_votes
0,2004,Alabama,AL,Autauga,John Kerry,democrat,4758.0,20081
1,2004,Alabama,AL,Autauga,George W. Bush,republican,15196.0,20081
2,2004,Alabama,AL,Baldwin,John Kerry,democrat,15599.0,69320
3,2004,Alabama,AL,Baldwin,George W. Bush,republican,52971.0,69320
4,2004,Alabama,AL,Barbour,John Kerry,democrat,4832.0,10777
...,...,...,...,...,...,...,...,...
6303,2004,Alaska,AK,District 38,George W. Bush,republican,2459.0,5075
6304,2004,Alaska,AK,District 39,John Kerry,democrat,2365.0,5568
6305,2004,Alaska,AK,District 39,George W. Bush,republican,2881.0,5568
6306,2004,Alaska,AK,District 40,John Kerry,democrat,2328.0,5788
6307,2004,Alaska,AK,District 40,George W. Bush,republican,3217.0,5788

In [36]:
election_data_2004_3

election_data_2004_3.to_csv (r'Resources/election_data2004.csv', index = False, header=True)