In [2]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import os
import csv
from census import Census
from us import states
from pprint import pprint
# Census API Key
# from config import api_key

In [4]:
temp_df = pd.read_csv("Resources/countyPop2010_2016_CLEAN.csv")
election_data_2008 = pd.read_csv("Resources/election_data2008.csv")
temp_df.head()

,County,State,2010,2011,2012,2013,2014,2015,2016
0,Autauga County,Alabama,"54,773","55,227","54,954","54,727","54,893","54,864","55,243"
1,Baldwin County,Alabama,"183,112","186,558","190,145","194,885","199,183","202,939","207,601"
2,Barbour County,Alabama,"27,327","27,341","27,169","26,937","26,755","26,283","25,806"
3,Bibb County,Alabama,"22,870","22,745","22,667","22,521","22,553","22,566","22,586"
4,Blount County,Alabama,"57,376","57,560","57,580","57,619","57,526","57,526","57,494"

In [5]:
new_df = pd.merge(t)

,year,state,state_code,county,candidate,party,candidate_votes,total_votes
0,2008,Alabama,AL,Autauga,Barack Obama,democrat,6093.0,23641
1,2008,Alabama,AL,Autauga,John McCain,republican,17403.0,23641
2,2008,Alabama,AL,Baldwin,Barack Obama,democrat,19386.0,81413
3,2008,Alabama,AL,Baldwin,John McCain,republican,61271.0,81413
4,2008,Alabama,AL,Barbour,Barack Obama,democrat,5697.0,11630
...,...,...,...,...,...,...,...,...
6303,2008,Alaska,AK,District 38,John McCain,republican,2056.0,4820
6304,2008,Alaska,AK,District 39,Barack Obama,democrat,2695.0,5184
6305,2008,Alaska,AK,District 39,John McCain,republican,2323.0,5184
6306,2008,Alaska,AK,District 40,Barack Obama,democrat,2137.0,5000
6307,2008,Alaska,AK,District 40,John McCain,republican,2686.0,5000

In [23]:
election_data_2008 = temp_df2.dropna()
election_data_2008.to_csv(r'Resources/election_data2008.csv', index = False, header=True)
election_data_2008

,year,state,state_code,county,candidate,party,candidate_votes,total_votes
21815,2008,Alabama,AL,Autauga,Barack Obama,democrat,6093.0,23641
21816,2008,Alabama,AL,Autauga,John McCain,republican,17403.0,23641
21818,2008,Alabama,AL,Baldwin,Barack Obama,democrat,19386.0,81413
21819,2008,Alabama,AL,Baldwin,John McCain,republican,61271.0,81413
21821,2008,Alabama,AL,Barbour,Barack Obama,democrat,5697.0,11630
...,...,...,...,...,...,...,...,...
50267,2008,Alaska,AK,District 38,John McCain,republican,2056.0,4820
50269,2008,Alaska,AK,District 39,Barack Obama,democrat,2695.0,5184
50270,2008,Alaska,AK,District 39,John McCain,republican,2323.0,5184
50272,2008,Alaska,AK,District 40,Barack Obama,democrat,2137.0,5000
50273,2008,Alaska,AK,District 40,John McCain,republican,2686.0,5000